name: Convert Pending Documents

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Groovy
        uses: WtfJoke/setup-groovy@v2.0.2
        with:
          groovy-version: 4.x

      - name: Download Aspose.Words
        # You may pin to the exact commit or the version.
        # uses: valadaptive/download-file-action@64a2f7bc6e92976a3ed6bc4c34297ec05f4549b4
        uses: ethanjli/cached-download-action@v0.1.2
        with:
          # The URL to fetch
          url: http://upload.liuzy88.com/aspose-words-21.1-jdk17-cracked.jar
          # The path to save the file to. Will be [default directory]/[URL file name] if not provided
          destination: aspose-words.jar
          # Additional key to match against when caching the file
          cache-key: aspose-words-21.1-jdk17
          
      - name: Run Doc Converter
        run: |
          TZ=Asia/Shanghai groovy -cp aspose-words.jar pending/process.groovy

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Convert Doc
